"""
AI Confidence module for Ripple.

Generates confidence badges and explanations for every PR Ripple opens,
based on observation patterns, fix type, language familiarity, and historical success.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class ConfidenceFactors:
    """Breakdown of confidence score components."""
    observation_score: float  # 0.0-1.0, based on how many times this pair was seen
    language_score: float     # 0.0-1.0, known language = higher
    fix_type_score: float     # 0.0-1.0, template > LLM
    history_score: float      # 0.0-1.0, merged PRs / total PRs


# Languages Ripple has strong fix generation support for
KNOWN_LANGUAGES = {
    "python", "typescript", "javascript", "go", "java", "rust",
    "ruby", "proto", "graphql", "kotlin", "swift", "csharp",
}

# Weights for each factor in the final score
WEIGHTS = {
    "observation": 0.35,
    "language": 0.20,
    "fix_type": 0.25,
    "history": 0.20,
}


def _observation_score(observation_count: int) -> float:
    """Score based on how many times this consumer-endpoint pair has been observed.

    Uses a logarithmic curve: 1 observation = 0.3, 5 = 0.6, 10+ = 0.8, 50+ = 0.95.
    """
    if observation_count <= 0:
        return 0.1
    if observation_count == 1:
        return 0.3
    if observation_count <= 3:
        return 0.45
    if observation_count <= 5:
        return 0.6
    if observation_count <= 10:
        return 0.75
    if observation_count <= 20:
        return 0.85
    if observation_count <= 50:
        return 0.92
    return 0.97


def _language_score(language: Optional[str]) -> float:
    """Score based on whether the consumer's language is well-supported."""
    if not language:
        return 0.4
    if language.lower() in KNOWN_LANGUAGES:
        return 0.95
    return 0.5


def _fix_type_score(fix_type: str) -> float:
    """Score based on how the fix was generated.

    Template-based fixes are more reliable than LLM-generated ones.
    """
    fix_type_lower = fix_type.lower() if fix_type else "unknown"
    if fix_type_lower in ("template", "deterministic", "ast"):
        return 0.95
    if fix_type_lower in ("llm", "ai", "generated"):
        return 0.70
    if fix_type_lower in ("hybrid", "template+llm"):
        return 0.82
    return 0.5


def _history_score(merged_count: int, total_count: int) -> float:
    """Score based on historical success rate of PRs for this consumer/repo.

    No history = neutral (0.5). High merge rate = high confidence.
    """
    if total_count == 0:
        return 0.5
    rate = merged_count / total_count
    # Bayesian smoothing: at least 3 PRs before we trust the rate
    if total_count < 3:
        return 0.5 + (rate - 0.5) * 0.3
    return max(0.1, min(0.98, rate))


def calculate_confidence(consumer: dict, breaking_change: dict, graph: dict) -> float:
    """Calculate confidence score (0-100) for a proposed fix.

    Args:
        consumer: Consumer info dict with keys like 'language', 'file', 'repo'.
        breaking_change: Breaking change dict with 'fix_type', 'field', 'endpoint'.
        graph: ConsumerGraph data with 'observation_count', 'merged_prs', 'total_prs'.

    Returns:
        Confidence as a float 0-100.
    """
    factors = get_confidence_factors(consumer, breaking_change, graph)
    score = (
        WEIGHTS["observation"] * factors.observation_score
        + WEIGHTS["language"] * factors.language_score
        + WEIGHTS["fix_type"] * factors.fix_type_score
        + WEIGHTS["history"] * factors.history_score
    )
    return round(score * 100, 1)


def get_confidence_factors(consumer: dict, breaking_change: dict, graph: dict) -> ConfidenceFactors:
    """Get the full breakdown of confidence factors."""
    return ConfidenceFactors(
        observation_score=_observation_score(graph.get("observation_count", 0)),
        language_score=_language_score(consumer.get("language")),
        fix_type_score=_fix_type_score(breaking_change.get("fix_type", "unknown")),
        history_score=_history_score(
            graph.get("merged_prs", 0),
            graph.get("total_prs", 0),
        ),
    )


def format_badge(confidence: float, observation_count: int) -> str:
    """Generate a one-line badge for the PR body.

    Example: '🧠 Generated by Ripple AI | Confidence: 94% | Based on 47 observed patterns in this repo'
    """
    return (
        f"🧠 Generated by Ripple AI | Confidence: {confidence:.0f}% "
        f"| Based on {observation_count} observed pattern{'s' if observation_count != 1 else ''} in this repo"
    )


def format_explanation(
    consumer: dict,
    breaking_change: dict,
    graph: dict,
    confidence: float,
) -> str:
    """Generate the explanation section for the PR body.

    Shows why Ripple made this fix and what evidence backs it.
    """
    observation_count = graph.get("observation_count", 0)
    endpoint = breaking_change.get("endpoint") or breaking_change.get("field") or "this endpoint"
    consumer_file = consumer.get("file", "the consumer file")
    consumer_line = consumer.get("line")

    location = f"`{consumer_file}"
    if consumer_line:
        location += f":{consumer_line}"
    location += "`"

    source_file = breaking_change.get("source_file") or breaking_change.get("contract", "the contract")

    lines = []
    lines.append("**Why this fix:**")

    if observation_count > 1:
        lines.append(
            f"Ripple learned that changes to `{source_file}` always require "
            f"updating {location} (seen {observation_count} time{'s' if observation_count != 1 else ''} "
            f"in git history)."
        )
    else:
        lines.append(
            f"Ripple detected that `{source_file}` changed and {location} "
            f"references the affected `{endpoint}`."
        )

    # Model and learning info
    lines.append(f"Model: PropBench v1 | Learning: enabled")

    # Factor breakdown for transparency
    factors = get_confidence_factors(consumer, breaking_change, graph)
    lines.append("")
    lines.append("<details><summary>Confidence breakdown</summary>")
    lines.append("")
    lines.append(f"| Factor | Score |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Observation history | {factors.observation_score:.0%} |")
    lines.append(f"| Language support | {factors.language_score:.0%} |")
    lines.append(f"| Fix generation method | {factors.fix_type_score:.0%} |")
    lines.append(f"| Historical success rate | {factors.history_score:.0%} |")
    lines.append(f"| **Overall confidence** | **{confidence:.0f}%** |")
    lines.append("")
    lines.append("</details>")

    return "\n".join(lines)


def format_pr_ai_section(consumer: dict, breaking_change: dict, graph: dict) -> str:
    """Combine badge + explanation into a full AI section for the PR body.

    This is the main entry point -- call this to get the complete section
    to append to any PR description.
    """
    confidence = calculate_confidence(consumer, breaking_change, graph)
    observation_count = graph.get("observation_count", 0)

    badge = format_badge(confidence, observation_count)
    explanation = format_explanation(consumer, breaking_change, graph, confidence)

    return f"---\n\n{badge}\n\n{explanation}"
