from __future__ import annotations
"""
ripple/app/confidence.py

Confidence Scoring — generates human-readable explanations for WHY
Ripple chose to fix a specific file.

Included in PR body so reviewers understand the reasoning:

## 🌊 Ripple — Confidence Report

| File | Confidence | Sources | Reason |
|------|-----------|---------|--------|
| client.py | 95% 🟢 | grep + history + playbook | Direct API call + co-changed 11/12 times |
| test_client.py | 78% 🟡 | playbook + history | Test files predicted by openapi playbook |
| docs/api.md | 45% 🟠 | grep only | Mentions endpoint name in comments |

"""

from dataclasses import dataclass


@dataclass
class ConfidenceLevel:
    """A confidence classification."""
    label: str       # "high", "medium", "low"
    emoji: str       # 🟢, 🟡, 🟠
    threshold: float # minimum confidence for this level
    action: str      # "auto-fix PR", "PR with warning", "comment only"


CONFIDENCE_LEVELS = [
    ConfidenceLevel("high", "🟢", 0.75, "Auto-fix PR"),
    ConfidenceLevel("medium", "🟡", 0.50, "PR with review note"),
    ConfidenceLevel("low", "🟠", 0.30, "Comment only (no PR)"),
    ConfidenceLevel("skip", "⚪", 0.0, "Logged but no action"),
]


def classify_confidence(score: float) -> ConfidenceLevel:
    """Classify a confidence score into a level."""
    for level in CONFIDENCE_LEVELS:
        if score >= level.threshold:
            return level
    return CONFIDENCE_LEVELS[-1]


def format_confidence_table(predictions: list[dict]) -> str:
    """
    Format ensemble predictions into a markdown table for PR body.
    
    Input: list of dicts from EnsembleConsumerFinder.find_all_consumers()
    Each: {"file": str, "confidence": float, "sources": list, "reasons": list}
    """
    if not predictions:
        return ""
    
    lines = [
        "## 🌊 Ripple — Confidence Report",
        "",
        "| File | Confidence | Sources | Why this file? |",
        "|------|-----------|---------|----------------|",
    ]
    
    for pred in predictions[:10]:  # Cap at 10 rows
        file_path = pred.get("file", "unknown")
        confidence = pred.get("confidence", 0)
        sources = pred.get("sources", [])
        reasons = pred.get("reasons", [])
        
        level = classify_confidence(confidence)
        pct = f"{int(confidence * 100)}%"
        sources_str = " + ".join(sources[:3])
        reason_str = reasons[0] if reasons else "Pattern match"
        
        # Truncate long file paths
        display_path = file_path if len(file_path) <= 40 else f"...{file_path[-37:]}"
        
        lines.append(
            f"| `{display_path}` | {pct} {level.emoji} | {sources_str} | {reason_str} |"
        )
    
    lines.append("")
    lines.append(f"*{len(predictions)} consumer(s) analyzed. "
                 f"Only files above {int(CONFIDENCE_LEVELS[0].threshold * 100)}% confidence get auto-fix PRs.*")
    
    return "\n".join(lines)


def format_pr_body(change_description: str, source_repo: str,
                   confidence: float, sources: list[str],
                   reasons: list[str], all_predictions: list[dict] = None) -> str:
    """
    Generate a complete PR body with confidence information.
    
    This replaces the generic "Auto-generated by Ripple" body with
    a detailed explanation of why this fix was created.
    """
    level = classify_confidence(confidence)
    
    body_parts = [
        f"## 🌊 Ripple",
        "",
        f"**API change in `{source_repo}`:** {change_description}",
        "",
        f"**Confidence:** {int(confidence * 100)}% {level.emoji} ({level.label})",
        f"**Detection sources:** {' + '.join(sources)}",
        "",
        "### Why this file?",
        "",
    ]
    
    for reason in reasons[:3]:
        body_parts.append(f"- {reason}")
    
    body_parts.append("")
    
    # Add full confidence table if we have predictions for other files
    if all_predictions and len(all_predictions) > 1:
        body_parts.append("### Other consumers detected")
        body_parts.append("")
        body_parts.append("| File | Confidence | Action |")
        body_parts.append("|------|-----------|--------|")
        
        for pred in all_predictions[:5]:
            if pred["file"] != "current":  # Skip current file
                p_level = classify_confidence(pred["confidence"])
                body_parts.append(
                    f"| `{pred['file'][:40]}` | {int(pred['confidence'] * 100)}% {p_level.emoji} | {p_level.action} |"
                )
        body_parts.append("")
    
    body_parts.extend([
        "---",
        "*Auto-generated by [Ripple](https://github.com/Aakash2408/ripple) — self-maintaining APIs*",
    ])
    
    return "\n".join(body_parts)


def should_create_pr(confidence: float, min_confidence: float = 0.5) -> bool:
    """Decide whether to create a PR based on confidence score."""
    return confidence >= min_confidence


def should_add_warning(confidence: float) -> bool:
    """Decide whether to add a 'needs review' warning to the PR."""
    level = classify_confidence(confidence)
    return level.label == "medium"
