from __future__ import annotations
"""
ripple/app/expand_contract.py

Expand+Contract Advisor — suggests safer migration patterns instead of
(or in addition to) fixing consumers after a breaking change.

Philosophy:
- Breaking changes are sometimes unavoidable (field removal, type change)
- But SOME breaking changes have a non-breaking alternative:
    * "Add required field" → add as OPTIONAL first, then require later
    * "Remove field" → deprecate first, remove in next major version
    * "Change field type" → add new field with new type, deprecate old

This module classifies each breaking change as:
- AVOIDABLE: a non-breaking alternative exists (suggest expand+contract)
- UNAVOIDABLE: no safe alternative (proceed with fix PRs)
- HYBRID: can be done safely but requires multi-step migration

For avoidable changes, Ripple generates a PR COMMENT suggesting the safer
approach instead of (or alongside) opening fix PRs.
"""

from dataclasses import dataclass
from typing import Optional
from .diff_engine import BreakingChange


@dataclass
class MigrationAdvice:
    """Advice for how to make a breaking change safely."""
    change: BreakingChange
    avoidable: bool           # True = could be done non-breakingly
    severity: str             # "warning" | "suggestion" | "info"
    pattern: str              # "expand-contract" | "deprecate-first" | "new-field" | "versioning"
    suggestion: str           # Human-readable suggestion
    steps: list[str]          # Step-by-step migration path
    fix_anyway: bool          # True = still offer to fix consumers (they chose to break)


def advise(change: BreakingChange) -> Optional[MigrationAdvice]:
    """
    Given a breaking change, determine if a safer alternative exists.
    Returns MigrationAdvice if applicable, None if the change is unavoidable.
    """
    advisors = [
        _advise_required_field_added,
        _advise_field_removed,
        _advise_field_type_changed,
        _advise_endpoint_removed,
        _advise_response_field_removed,
        _advise_required_header_added,
        _advise_channel_removed,
    ]
    
    for advisor in advisors:
        advice = advisor(change)
        if advice:
            return advice
    
    return None


def format_pr_comment(advice: MigrationAdvice) -> str:
    """Format the advice as a GitHub/GitLab PR comment."""
    emoji = "⚠️" if advice.severity == "warning" else "💡"
    
    lines = [
        f"## {emoji} Ripple — Breaking Change Detected",
        "",
        f"**Change:** `{change_summary(advice.change)}`",
        f"**Impact:** This will break consumers of `{advice.change.method.upper()} {advice.change.path}`",
        "",
    ]
    
    if advice.avoidable:
        lines.extend([
            f"### 💡 Safer alternative: {advice.pattern.replace('-', ' ').title()}",
            "",
            advice.suggestion,
            "",
            "**Migration steps:**",
        ])
        for i, step in enumerate(advice.steps, 1):
            lines.append(f"{i}. {step}")
        lines.extend([
            "",
            "---",
            "",
            "**Options:**",
            f"- ✅ Switch to the safe migration (no consumers break)",
            f"- ⚡ Proceed with breaking change (Ripple will open fix PRs in {advice.change.method} consumers)",
        ])
    else:
        lines.extend([
            "This breaking change has **no non-breaking alternative**.",
            "Ripple will open fix PRs in affected consumers.",
        ])
    
    lines.extend([
        "",
        "---",
        "*Auto-generated by [Ripple](https://github.com/Aakash2408/ripple) — self-maintaining APIs*",
    ])
    
    return "\n".join(lines)


def change_summary(change: BreakingChange) -> str:
    """One-line summary of a breaking change."""
    return f"{change.change_type}: '{change.field_name}' in {change.method.upper()} {change.path}"


# === Advisor Functions ===

def _advise_required_field_added(change: BreakingChange) -> Optional[MigrationAdvice]:
    """Adding a required field can always be done as optional-first."""
    if change.change_type != "added_required_field":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=True,
        severity="warning",
        pattern="expand-contract",
        suggestion=f"Instead of adding `{change.field_name}` as required immediately, add it as **optional** first. Once all consumers are sending it, make it required.",
        steps=[
            f"Add `{change.field_name}` as **optional** (not in `required` array)",
            "Deploy — no consumers break",
            f"Migrate consumers to include `{change.field_name}` in their requests",
            f"Once all consumers send `{change.field_name}`, make it required",
            "Deploy — safe because everyone already sends it",
        ],
        fix_anyway=True,
    )


def _advise_field_removed(change: BreakingChange) -> Optional[MigrationAdvice]:
    """Removing a field can be done with deprecation-first."""
    if change.change_type != "removed_field":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=True,
        severity="suggestion",
        pattern="deprecate-first",
        suggestion=f"Instead of removing `{change.field_name}` immediately, mark it as **deprecated** first. Remove it in the next major version after consumers stop sending it.",
        steps=[
            f"Mark `{change.field_name}` as deprecated (add `deprecated: true` in spec)",
            "Deploy — consumers see deprecation warning but don't break",
            "Monitor: wait until no consumers send the deprecated field",
            f"Remove `{change.field_name}` in the next major version",
        ],
        fix_anyway=True,
    )


def _advise_field_type_changed(change: BreakingChange) -> Optional[MigrationAdvice]:
    """Type changes can be done with a new field + deprecation of old."""
    if change.change_type != "field_type_changed":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=True,
        severity="warning",
        pattern="new-field",
        suggestion=f"Instead of changing `{change.field_name}` type from {change.field_type}, add a **new field** with the new type and deprecate the old one.",
        steps=[
            f"Add new field `{change.field_name}_v2` with the new type",
            f"Mark old `{change.field_name}` as deprecated",
            "Deploy — consumers can migrate at their own pace",
            f"Once all consumers use `{change.field_name}_v2`, remove the old field",
        ],
        fix_anyway=True,
    )


def _advise_endpoint_removed(change: BreakingChange) -> Optional[MigrationAdvice]:
    """Endpoint removal should go through deprecation + versioning."""
    if change.change_type != "endpoint_removed":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=True,
        severity="warning",
        pattern="versioning",
        suggestion=f"Instead of removing `{change.field_name}` immediately, deprecate it and introduce a replacement under a new version prefix (e.g., /v2/).",
        steps=[
            f"Mark `{change.field_name}` as deprecated in the spec",
            "Add the replacement endpoint (e.g., under /v2/)",
            "Deploy — old endpoint still works, consumers can migrate",
            "Set a sunset date (e.g., 90 days)",
            "Remove after sunset date passes",
        ],
        fix_anyway=False,  # Can't "fix" a removed endpoint — consumers must migrate
    )


def _advise_response_field_removed(change: BreakingChange) -> Optional[MigrationAdvice]:
    """Response field removal — usually unavoidable but can deprecate."""
    if change.change_type != "response_field_removed":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=True,
        severity="suggestion",
        pattern="deprecate-first",
        suggestion=f"Response field `{change.field_name}` removal can be softened by returning null/empty for a deprecation period before removing entirely.",
        steps=[
            f"Start returning `{change.field_name}: null` (or empty string) instead of removing",
            "Add deprecation notice in API docs",
            "Wait for consumers to stop reading the field",
            "Then remove entirely",
        ],
        fix_anyway=True,
    )


def _advise_required_header_added(change: BreakingChange) -> Optional[MigrationAdvice]:
    """Required header addition — same as required field (expand-contract)."""
    if change.change_type != "required_header_added":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=True,
        severity="warning",
        pattern="expand-contract",
        suggestion=f"Instead of requiring header `{change.field_name}` immediately, make your server accept requests without it (with a default/fallback) while consumers add it.",
        steps=[
            f"Accept requests WITHOUT `{change.field_name}` (use default value server-side)",
            "Document the new header and encourage consumers to send it",
            "Monitor: wait until all consumers send the header",
            "Then enforce it as required",
        ],
        fix_anyway=True,
    )


def _advise_channel_removed(change: BreakingChange) -> Optional[MigrationAdvice]:
    """AsyncAPI channel removal — unavoidable but can route to new channel."""
    if change.change_type != "channel_removed":
        return None
    
    return MigrationAdvice(
        change=change,
        avoidable=False,  # Can't keep a channel that shouldn't exist
        severity="info",
        pattern="deprecate-first",
        suggestion=f"Channel `{change.field_name}` removal is unavoidable, but subscribers should be notified in advance.",
        steps=[
            "Publish a 'channel-deprecated' meta-event on the channel",
            "Add the replacement channel to the spec",
            "Give consumers time to migrate subscriptions",
            "Remove the old channel",
        ],
        fix_anyway=False,
    )


# === Batch Analysis ===

def analyze_changes(changes: list[BreakingChange]) -> dict:
    """
    Analyze a list of breaking changes and produce a summary.
    
    Returns:
        {
            "total": N,
            "avoidable": N,
            "unavoidable": N,
            "advice": [MigrationAdvice, ...],
            "summary": "3/5 breaking changes could be done non-breakingly"
        }
    """
    advice_list = []
    for change in changes:
        advice = advise(change)
        if advice:
            advice_list.append(advice)
    
    avoidable = sum(1 for a in advice_list if a.avoidable)
    unavoidable = len(changes) - avoidable
    
    return {
        "total": len(changes),
        "avoidable": avoidable,
        "unavoidable": unavoidable,
        "advice": advice_list,
        "summary": f"{avoidable}/{len(changes)} breaking changes could be done non-breakingly" if changes else "No breaking changes",
    }
