"""
ripple/app/impact_report.py

Change Impact Report — generates a detailed manifest of what was changed,
what was scanned but deliberately left alone, and why.

This goes into the PR body so reviewers understand the full scope at a glance.

Categories tracked:
  - CONTRACTS: spec files, proto definitions, schema files
  - CODE: source code that directly references the changed field/type
  - TESTS: test files that exercise the changed behavior
  - DOCS: documentation files (README, API docs, guides)
  - EXAMPLES: example code, tutorials, sample apps
  - CONFIG: configuration files that reference the changed entity
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class Category(str, Enum):
    CONTRACT = "contract"
    CODE = "code"
    TEST = "test"
    DOCS = "docs"
    EXAMPLE = "example"
    CONFIG = "config"


class Action(str, Enum):
    FIXED = "fixed"          # Code was modified to fix the break
    LEFT_ALONE = "left"      # Scanned, determined safe to leave
    NEEDS_MANUAL = "manual"  # Flagged for human review
    NOT_FOUND = "skipped"    # Category wasn't found in repo


@dataclass
class ImpactItem:
    """A single file or area that was assessed."""
    file_path: str
    category: Category
    action: Action
    reason: str
    line_numbers: Optional[str] = None  # e.g. "L42-L45"


@dataclass
class ImpactReport:
    """Full impact report for a breaking change propagation."""
    breaking_change_summary: str
    source_file: str
    items: list[ImpactItem] = field(default_factory=list)
    
    @property
    def fixed_items(self) -> list[ImpactItem]:
        return [i for i in self.items if i.action == Action.FIXED]
    
    @property
    def left_alone_items(self) -> list[ImpactItem]:
        return [i for i in self.items if i.action == Action.LEFT_ALONE]
    
    @property
    def needs_manual_items(self) -> list[ImpactItem]:
        return [i for i in self.items if i.action == Action.NEEDS_MANUAL]
    
    def to_markdown(self) -> str:
        """Render the impact report as markdown for PR body."""
        lines = []
        lines.append("## 🌊 Ripple — Change Impact Report")
        lines.append("")
        lines.append(f"**Breaking change:** {self.breaking_change_summary}")
        lines.append(f"**Source:** `{self.source_file}`")
        lines.append("")
        
        # Fixed section
        if self.fixed_items:
            lines.append("### ✅ Changed (auto-fixed)")
            lines.append("")
            lines.append("| File | Category | What was done |")
            lines.append("|------|----------|---------------|")
            for item in self.fixed_items:
                loc = f" ({item.line_numbers})" if item.line_numbers else ""
                lines.append(f"| `{item.file_path}`{loc} | {_category_emoji(item.category)} {item.category.value} | {item.reason} |")
            lines.append("")
        
        # Deliberately left alone section
        if self.left_alone_items:
            lines.append("### 📝 Scanned — Deliberately Left Alone")
            lines.append("")
            lines.append("| File | Category | Why it's safe |")
            lines.append("|------|----------|---------------|")
            for item in self.left_alone_items:
                lines.append(f"| `{item.file_path}` | {_category_emoji(item.category)} {item.category.value} | {item.reason} |")
            lines.append("")
        
        # Needs manual review section
        if self.needs_manual_items:
            lines.append("### ⚠️ Needs Manual Review")
            lines.append("")
            lines.append("| File | Category | Why |")
            lines.append("|------|----------|-----|")
            for item in self.needs_manual_items:
                lines.append(f"| `{item.file_path}` | {_category_emoji(item.category)} {item.category.value} | {item.reason} |")
            lines.append("")
        
        # Summary stats
        lines.append("---")
        lines.append("")
        lines.append(f"**Summary:** {len(self.fixed_items)} fixed · {len(self.left_alone_items)} left alone · {len(self.needs_manual_items)} need manual review")
        lines.append("")
        lines.append("*Ripple only auto-fixes code that would **break**. Docs, examples, and tests that still pass are flagged but not modified — you decide.*")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by [Ripple](https://aakash2408.github.io/ripple) 🌊 — self-maintaining APIs*")
        
        return "\n".join(lines)


def generate_impact_report(
    breaking_change_summary: str,
    source_file: str,
    fixed_files: list[dict],
    scanned_files: list[dict],
    repo_files: list[str] = None,
) -> ImpactReport:
    """
    Generate an impact report from fix results and repo scan.
    
    Args:
        breaking_change_summary: Human-readable description (e.g. "Removed field `phone_number` from User message")
        source_file: The spec file that changed (e.g. "proto/user.proto")
        fixed_files: List of dicts with {file_path, reason, line_numbers}
        scanned_files: List of dicts with {file_path, category, action, reason}
        repo_files: Optional full list of files in repo (for coverage assessment)
    
    Returns:
        ImpactReport ready to render as markdown
    """
    report = ImpactReport(
        breaking_change_summary=breaking_change_summary,
        source_file=source_file,
    )
    
    # Add fixed items
    for f in fixed_files:
        report.items.append(ImpactItem(
            file_path=f["file_path"],
            category=_classify_file(f["file_path"]),
            action=Action.FIXED,
            reason=f.get("reason", "Removed broken reference"),
            line_numbers=f.get("line_numbers"),
        ))
    
    # Add scanned/left-alone items
    for s in scanned_files:
        action = Action(s.get("action", "left"))
        report.items.append(ImpactItem(
            file_path=s["file_path"],
            category=Category(s.get("category", _classify_file(s["file_path"]).value)),
            action=action,
            reason=s.get("reason", "No breaking reference found"),
        ))
    
    # If repo files provided, check for docs/examples/tests not yet scanned
    if repo_files:
        scanned_paths = {i.file_path for i in report.items}
        for f in repo_files:
            if f in scanned_paths:
                continue
            cat = _classify_file(f)
            if cat in (Category.DOCS, Category.EXAMPLE, Category.TEST):
                # Flag unscanned docs/tests/examples as needing manual review
                report.items.append(ImpactItem(
                    file_path=f,
                    category=cat,
                    action=Action.NEEDS_MANUAL,
                    reason="Not scanned — may reference changed entity",
                ))
    
    return report


def classify_consumer_files(
    consumer_files: list[str],
    changed_field: str,
    file_contents: dict[str, str] = None,
) -> list[dict]:
    """
    Classify consumer files as safe-to-leave or needs-manual-review.
    
    For each file that WASN'T fixed, determine if it's safe:
    - Test file that doesn't reference the field → safe
    - Doc file with no mention → safe
    - Example with the field referenced → needs manual
    """
    results = []
    
    for file_path in consumer_files:
        cat = _classify_file(file_path)
        content = (file_contents or {}).get(file_path, "")
        
        # Check if file mentions the changed field
        mentions_field = changed_field.lower() in content.lower() if content else False
        
        if not mentions_field:
            results.append({
                "file_path": file_path,
                "category": cat.value,
                "action": "left",
                "reason": f"No reference to `{changed_field}` found",
            })
        elif cat == Category.TEST:
            results.append({
                "file_path": file_path,
                "category": cat.value,
                "action": "left",
                "reason": f"Test references `{changed_field}` but still passes (field was optional)",
            })
        elif cat == Category.DOCS:
            results.append({
                "file_path": file_path,
                "category": cat.value,
                "action": "manual",
                "reason": f"Documentation mentions `{changed_field}` — update recommended",
            })
        elif cat == Category.EXAMPLE:
            results.append({
                "file_path": file_path,
                "category": cat.value,
                "action": "manual",
                "reason": f"Example uses `{changed_field}` — may confuse new users",
            })
        else:
            results.append({
                "file_path": file_path,
                "category": cat.value,
                "action": "manual",
                "reason": f"References `{changed_field}` — review needed",
            })
    
    return results


def _classify_file(file_path: str) -> Category:
    """Classify a file into a category based on its path and extension."""
    path_lower = file_path.lower()
    
    # Tests
    if any(p in path_lower for p in ["test", "spec", "__tests__", "_test.", ".test."]):
        return Category.TEST
    
    # Docs
    if any(p in path_lower for p in ["readme", "doc/", "docs/", "changelog", ".md", "api-reference"]):
        return Category.DOCS
    
    # Examples
    if any(p in path_lower for p in ["example", "sample", "demo", "tutorial"]):
        return Category.EXAMPLE
    
    # Config
    if any(p in path_lower for p in [".yaml", ".yml", ".toml", ".ini", ".env", "config"]):
        return Category.CONFIG
    
    # Contracts/specs
    if any(p in path_lower for p in [".proto", ".graphql", ".gql", "openapi", "swagger", ".avsc", ".thrift"]):
        return Category.CONTRACT
    
    # Default: code
    return Category.CODE


def _category_emoji(cat: Category) -> str:
    """Get emoji for a category."""
    return {
        Category.CONTRACT: "📋",
        Category.CODE: "💻",
        Category.TEST: "🧪",
        Category.DOCS: "📝",
        Category.EXAMPLE: "📖",
        Category.CONFIG: "⚙️",
    }.get(cat, "📄")
