"""
ripple/app/pr_engine.py

PR Engine — creates GitHub pull requests with generated fixes.

For each fix:
1. Create a branch in the consumer repo
2. Commit the fixed file
3. Open a PR with explanation

Requires: GITHUB_TOKEN environment variable with repo write access.
For the demo: works with personal repos or a GitHub App installation token.
"""

import os
import base64
from dataclasses import dataclass
from typing import Optional
from urllib.request import Request, urlopen
from urllib.error import HTTPError
import json

from .diff_engine import BreakingChange
from .fix_generator import GeneratedFix


GITHUB_API = "https://api.github.com"


@dataclass
class CreatedPR:
    """A successfully created pull request."""
    repo: str
    pr_number: int
    pr_url: str
    branch_name: str
    title: str


def create_prs(
    fixes: list[GeneratedFix],
    breaking_change: BreakingChange,
    source_repo: str = "api-service",
    dry_run: bool = False,
) -> list[CreatedPR]:
    """
    Create PRs for all generated fixes.
    
    Each fix gets its own branch and PR in the consumer's repo.
    """
    token = os.environ.get("GITHUB_TOKEN")
    if not token and not dry_run:
        print("  ⚠️  GITHUB_TOKEN not set. Use --dry-run to preview PRs.")
        return []
    
    created = []
    
    for fix in fixes:
        pr = create_pr(fix, breaking_change, source_repo, token, dry_run)
        if pr:
            created.append(pr)
    
    return created


def create_pr(
    fix: GeneratedFix,
    breaking_change: BreakingChange,
    source_repo: str,
    token: Optional[str],
    dry_run: bool = False,
) -> Optional[CreatedPR]:
    """Create a single PR for one fix."""
    
    # Determine the repo from the file path
    # For demo: we need repo owner/name. In real usage this comes from GitHub App installation.
    repo = _infer_repo(fix.consumer.file_path)
    
    branch_name = f"ripple/fix-{breaking_change.field_name}-{breaking_change.path.replace('/', '-').strip('-')}"
    title = f"fix: Add required field '{breaking_change.field_name}' to {breaking_change.method.upper()} {breaking_change.path}"
    
    body = _format_pr_body(fix, breaking_change, source_repo)
    
    if dry_run:
        print(f"  📋 [DRY RUN] Would create PR in {repo}:")
        print(f"     Branch: {branch_name}")
        print(f"     Title:  {title}")
        print(f"     File:   {fix.consumer.file_path}")
        print(f"     Diff:   {len(fix.diff)} chars")
        print()
        return CreatedPR(
            repo=repo or "unknown",
            pr_number=0,
            pr_url="(dry-run)",
            branch_name=branch_name,
            title=title,
        )
    
    if not repo or not token:
        return None
    
    try:
        # 1. Get the default branch SHA
        default_branch = _get_default_branch(repo, token)
        base_sha = _get_branch_sha(repo, default_branch, token)
        
        # 2. Create the branch
        _create_branch(repo, branch_name, base_sha, token)
        
        # 3. Update the file on the new branch
        file_path = _relative_file_path(fix.consumer.file_path, repo)
        _update_file(repo, file_path, fix.fixed_code, branch_name, title, token)
        
        # 4. Create the PR
        pr_number, pr_url = _create_pull_request(
            repo, branch_name, default_branch, title, body, token
        )
        
        return CreatedPR(
            repo=repo,
            pr_number=pr_number,
            pr_url=pr_url,
            branch_name=branch_name,
            title=title,
        )
    
    except Exception as e:
        print(f"  ❌ Failed to create PR in {repo}: {e}")
        return None


def _format_pr_body(fix: GeneratedFix, change: BreakingChange, source_repo: str) -> str:
    """Format the PR description."""
    return f"""## 🌊 Ripple — Automated API Change Propagation

### Breaking Change Detected

| Field | Value |
|-------|-------|
| **Source** | `{source_repo}` |
| **Endpoint** | `{change.method.upper()} {change.path}` |
| **Change** | {change.change_type} |
| **Field** | `{change.field_name}` ({change.field_type}) |

### What changed

{change.description}

### Fix applied

{fix.explanation}

### Diff

```diff
{fix.diff}
```

---
*This PR was automatically generated by [Ripple](https://ripple.dev) — self-maintaining APIs.*
*Please review the fix and add appropriate default values or tests before merging.*
"""


def _infer_repo(file_path: str) -> Optional[str]:
    """
    Infer GitHub repo from file path.
    
    In real usage: the GitHub App installation knows which repos it has access to.
    For demo: look for .git/config or use a mapping.
    """
    # This is a placeholder — in production, the GitHub App webhook
    # provides the repo context directly.
    # For now, return None (will use --repo flag in CLI)
    return os.environ.get("RIPPLE_TARGET_REPO")


def _relative_file_path(absolute_path: str, repo: str) -> str:
    """Convert absolute file path to repo-relative path."""
    # Strip everything up to and including the repo name
    parts = absolute_path.split("/")
    # Find the part that looks like it's after the repo root
    for i, part in enumerate(parts):
        if part == "src" or part == "lib" or part == "app":
            return "/".join(parts[i:])
    return absolute_path.split("/")[-1]


# === GitHub API Helpers ===

def _github_request(method: str, path: str, token: str, data: dict = None) -> dict:
    """Make an authenticated GitHub API request."""
    url = f"{GITHUB_API}{path}"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    
    body = json.dumps(data).encode() if data else None
    if body:
        headers["Content-Type"] = "application/json"
    
    req = Request(url, data=body, headers=headers, method=method)
    
    try:
        with urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except HTTPError as e:
        error_body = e.read().decode() if e.readable() else ""
        raise Exception(f"GitHub API {method} {path}: {e.code} {error_body[:200]}")


def _get_default_branch(repo: str, token: str) -> str:
    """Get the default branch name for a repo."""
    data = _github_request("GET", f"/repos/{repo}", token)
    return data.get("default_branch", "main")


def _get_branch_sha(repo: str, branch: str, token: str) -> str:
    """Get the SHA of a branch's HEAD."""
    data = _github_request("GET", f"/repos/{repo}/git/ref/heads/{branch}", token)
    return data["object"]["sha"]


def _create_branch(repo: str, branch_name: str, sha: str, token: str):
    """Create a new branch from a SHA."""
    _github_request("POST", f"/repos/{repo}/git/refs", token, {
        "ref": f"refs/heads/{branch_name}",
        "sha": sha,
    })


def _update_file(repo: str, file_path: str, content: str, branch: str, message: str, token: str):
    """Update (or create) a file on a branch."""
    # First try to get the current file SHA (needed for updates)
    try:
        existing = _github_request("GET", f"/repos/{repo}/contents/{file_path}?ref={branch}", token)
        sha = existing["sha"]
    except Exception:
        sha = None
    
    data = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch": branch,
    }
    if sha:
        data["sha"] = sha
    
    _github_request("PUT", f"/repos/{repo}/contents/{file_path}", token, data)


def _create_pull_request(repo: str, head: str, base: str, title: str, body: str, token: str) -> tuple[int, str]:
    """Create a pull request."""
    data = _github_request("POST", f"/repos/{repo}/pulls", token, {
        "title": title,
        "body": body,
        "head": head,
        "base": base,
    })
    return data["number"], data["html_url"]


def format_prs(prs: list[CreatedPR]) -> str:
    """Format created PRs for display."""
    if not prs:
        return "  No PRs created."
    
    lines = [f"  Created {len(prs)} PR(s):", ""]
    for pr in prs:
        lines.append(f"  ✅ {pr.repo}")
        lines.append(f"     PR #{pr.pr_number}: {pr.title}")
        lines.append(f"     {pr.pr_url}")
        lines.append("")
    
    return "\n".join(lines)
