"""
ripple/app/pr_ledger.py

Which pattern produced which PR -- written when the PR is opened, read when it
closes.

WHY THIS EXISTS
---------------
`learn_from_merged_pr(pattern_id)` needs a pattern id. A `pull_request.closed`
webhook carries a PR number. NOTHING linked the two, so webhook.py tried to pass
the raw facts instead:

    learn_from_merged_pr(trigger_diff=..., fix_diff=..., language=...,
                         field_name=..., change_type=..., store=...)

against a one-parameter function. Every merged Ripple PR raised TypeError,
`except Exception: return {"status": "learn_error"}` swallowed it, and no
_log_activity fired because the log line sat after the failing call in the same
try. The RAG store stayed at 0 patterns and the failure was invisible. The missing
piece was never the call -- it was this link.

IT IS ALSO THE IDENTITY CHECK
-----------------------------
The previous test for "is this Ripple's PR" was

    if "Generated by" not in pr_body and "Ripple" not in pr_body:

a substring scan of text a human writes, which matches any PR that merely MENTIONS
Ripple. Attributing a stranger's merge to one of Ripple's patterns would raise that
pattern's confidence on unrelated evidence. A ledger row is exact: no row means not
ours, and the honest response is to record nothing -- the same rule as
`validated=None -> REVIEW`.

DURABILITY IS THE POINT
-----------------------
Rows live beside activity.json on the mounted volume. Before /app/data was
mounted, `event_count` reset to 0 on every redeploy; a learning ledger with that
property would silently discard every outcome it ever saw, which is worse than not
having one because the counts would look plausible.
"""
from __future__ import annotations

import json
import os
import threading
import time
from pathlib import Path
from typing import Optional

#: Same candidate ladder as activity.py / token_store.py / rag_store.py. Repeated
#: rather than shared because those four modules must not import each other --
#: activity is imported by webhook at module scope and a cycle here would break
#: the request path.
_DATA_DIR_CANDIDATES = [
    os.environ.get("RIPPLE_DATA_DIR", ""),
    "/app/data",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data"),
    "/tmp/ripple-data",
]

#: A ledger row is small and a repo is long-lived, so the cap is generous -- but it
#: is a cap, because an unbounded file on a mounted volume is an outage waiting for
#: a busy month. Oldest-first eviction: an old PR's outcome has already been
#: recorded or never will be.
_MAX_ROWS = 5000

_lock = threading.Lock()
_rows: dict = {}
_outcomes: list = []
_loaded = False


def _store_dir() -> Path:
    for candidate in _DATA_DIR_CANDIDATES:
        if not candidate:
            continue
        p = Path(candidate)
        try:
            p.mkdir(parents=True, exist_ok=True)
            probe = p / ".write_test"
            probe.write_text("ok")
            probe.unlink()
            return p
        except (IOError, OSError):
            continue
    return Path("/tmp")


def _store_path() -> Path:
    return _store_dir() / "pr_ledger.json"


def _load() -> None:
    global _loaded, _rows, _outcomes
    if _loaded:
        return
    _loaded = True
    try:
        with open(_store_path()) as fh:
            blob = json.load(fh)
        _rows = blob.get("rows", {}) or {}
        _outcomes = blob.get("outcomes", []) or []
    except (IOError, OSError, ValueError):
        # A corrupt or absent ledger starts empty rather than raising. An
        # unreadable ledger means "we cannot attribute", which the caller already
        # handles by recording nothing -- the same degradation as a missing row.
        _rows, _outcomes = {}, []


def _persist() -> None:
    try:
        tmp = _store_path().with_suffix(".tmp")
        with open(tmp, "w") as fh:
            json.dump({"rows": _rows, "outcomes": _outcomes[-_MAX_ROWS:]}, fh)
        os.replace(tmp, _store_path())
    except (IOError, OSError):
        # Best effort. Losing a write costs one training example; raising here
        # would cost the PR that was being opened.
        pass


def record_open(pr_url: str, *, pattern_id: str, source: str, change_type: str,
                language: str, field_name: str, consumer_file: str,
                repo: str, validated, level: str) -> None:
    """Remember what produced this PR. Called ONCE PER CONSUMER FILE.

    `source` distinguishes the generator -- "pattern" (a stored FixPattern, so
    `pattern_id` is real), "template" (deterministic codemod, no pattern yet) or
    "llm". A template-generated fix has nothing to credit on merge, which is a
    fact the outcome handler needs rather than a gap it has to infer.

    THIS MERGES RATHER THAN OVERWRITES, and that is the whole point.

    Ripple opens ONE PR per repo covering ALL of that repo's consumers: the branch
    name is derived from the FIELD, so the second consumer hits the existing branch,
    appends a commit, and gets back the SAME pr_url. Live proof -- billing-api PR #5
    is 2 commits / 2 files / 1 PR.

    This function used to assign `_rows[pr_url] = {...}`, so N consumers wrote N
    rows to one key and only the LAST survived. Every other consumer was silently
    dropped, and contamination then read the merge as "N files changed but Ripple
    proposed 1" and refused to learn from it -- which is the common case, so the
    store could never gain a pattern.

    Merging here keeps the three per-consumer call sites untouched. Restructuring
    the loops to accumulate before writing would put the same obligation in three
    places, which is exactly how the diff contract ended up wired in one caller and
    bypassed by another.

    ABSENCE NEVER OVERWRITES PRESENCE. Consumers of one field can come from
    different generators, and `_pattern_id_from_explanation` returns "" for a
    template fix -- so a plain dict update would let a later empty pattern_id erase
    a real one and make the merge unattributable. Same rule as the provenance
    ladder.
    """
    if not pr_url:
        return
    with _lock:
        _load()
        existing = _rows.get(pr_url)

        if existing is None:
            _rows[pr_url] = {
                "pattern_id": pattern_id or "",
                "source": source,
                "change_type": change_type,
                "language": language,
                "field_name": field_name,
                "consumer_file": consumer_file,
                #: Every file Ripple proposed under this PR. Contamination is
                #: bounded against this set, not against a count of 1.
                "proposed_files": [consumer_file] if consumer_file else [],
                "repo": repo,
                "validated": validated,
                "level": level,
                "opened_at": time.time(),
            }
        else:
            files = list(existing.get("proposed_files") or [])
            if consumer_file and consumer_file not in files:
                files.append(consumer_file)
            existing["proposed_files"] = files

            # Fill only what is missing; never replace a real value with an empty
            # one. `opened_at` keeps the FIRST write's time so eviction order
            # reflects when the PR was actually opened.
            if not existing.get("pattern_id") and pattern_id:
                existing["pattern_id"] = pattern_id
            if not existing.get("consumer_file") and consumer_file:
                existing["consumer_file"] = consumer_file
            for key, value in (("source", source), ("change_type", change_type),
                               ("language", language), ("field_name", field_name),
                               ("repo", repo), ("level", level)):
                if not existing.get(key) and value:
                    existing[key] = value
            # `validated` is tri-state: None means "could not check", which must
            # not be upgraded by a later consumer that happened to validate. Only
            # a False may sharpen it -- one unvalidated file makes the PR's claim
            # weaker, never stronger.
            if existing.get("validated") is not False and validated is False:
                existing["validated"] = False

        if len(_rows) > _MAX_ROWS:
            for key in sorted(_rows, key=lambda k: _rows[k].get("opened_at", 0.0)
                              )[:len(_rows) - _MAX_ROWS]:
                _rows.pop(key, None)
        _persist()


def lookup(pr_url: str) -> Optional[dict]:
    """The provenance row for a PR, or None when Ripple did not open it."""
    with _lock:
        _load()
        row = _rows.get(pr_url)
        return dict(row) if row else None


def record_outcome(pr_url: str, outcome: str, detail: dict = None) -> None:
    """Append the terminal state of a PR Ripple opened.

    Kept separate from the pattern counters on purpose: this is the audit trail of
    what the world decided, and it stays true even when the outcome is one Ripple
    must NOT learn from (a human-edited merge, a contaminated sample). The counters
    are a derived view; this is the record.
    """
    with _lock:
        _load()
        _outcomes.append({
            "pr_url": pr_url,
            "outcome": outcome,
            "at": time.time(),
            **(detail or {}),
        })
        _persist()


def all_outcomes() -> list:
    with _lock:
        _load()
        return list(_outcomes)


def stats() -> dict:
    with _lock:
        _load()
        counts: dict = {}
        for row in _outcomes:
            counts[row.get("outcome", "?")] = counts.get(row.get("outcome", "?"), 0) + 1
        return {"open_rows": len(_rows), "outcomes": len(_outcomes),
                "by_outcome": counts, "path": str(_store_path())}


def reset_for_tests() -> None:
    """Clear in-memory state. Tests only -- never called from the request path."""
    global _loaded, _rows, _outcomes
    with _lock:
        _rows, _outcomes, _loaded = {}, [], True
