"""
ripple/app/pr_ledger.py

Which pattern produced which PR -- written when the PR is opened, read when it
closes.

WHY THIS EXISTS
---------------
`learn_from_merged_pr(pattern_id)` needs a pattern id. A `pull_request.closed`
webhook carries a PR number. NOTHING linked the two, so webhook.py tried to pass
the raw facts instead:

    learn_from_merged_pr(trigger_diff=..., fix_diff=..., language=...,
                         field_name=..., change_type=..., store=...)

against a one-parameter function. Every merged Ripple PR raised TypeError,
`except Exception: return {"status": "learn_error"}` swallowed it, and no
_log_activity fired because the log line sat after the failing call in the same
try. The RAG store stayed at 0 patterns and the failure was invisible. The missing
piece was never the call -- it was this link.

IT IS ALSO THE IDENTITY CHECK
-----------------------------
The previous test for "is this Ripple's PR" was

    if "Generated by" not in pr_body and "Ripple" not in pr_body:

a substring scan of text a human writes, which matches any PR that merely MENTIONS
Ripple. Attributing a stranger's merge to one of Ripple's patterns would raise that
pattern's confidence on unrelated evidence. A ledger row is exact: no row means not
ours, and the honest response is to record nothing -- the same rule as
`validated=None -> REVIEW`.

DURABILITY IS THE POINT
-----------------------
Rows live beside activity.json on the mounted volume. Before /app/data was
mounted, `event_count` reset to 0 on every redeploy; a learning ledger with that
property would silently discard every outcome it ever saw, which is worse than not
having one because the counts would look plausible.
"""
from __future__ import annotations

import json
import os
import threading
import time
from pathlib import Path
from typing import Optional

#: Same candidate ladder as activity.py / token_store.py / rag_store.py. Repeated
#: rather than shared because those four modules must not import each other --
#: activity is imported by webhook at module scope and a cycle here would break
#: the request path.
_DATA_DIR_CANDIDATES = [
    os.environ.get("RIPPLE_DATA_DIR", ""),
    "/app/data",
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data"),
    "/tmp/ripple-data",
]

#: A ledger row is small and a repo is long-lived, so the cap is generous -- but it
#: is a cap, because an unbounded file on a mounted volume is an outage waiting for
#: a busy month. Oldest-first eviction: an old PR's outcome has already been
#: recorded or never will be.
_MAX_ROWS = 5000

_lock = threading.Lock()
_rows: dict = {}
_outcomes: list = []
_loaded = False


def _store_dir() -> Path:
    for candidate in _DATA_DIR_CANDIDATES:
        if not candidate:
            continue
        p = Path(candidate)
        try:
            p.mkdir(parents=True, exist_ok=True)
            probe = p / ".write_test"
            probe.write_text("ok")
            probe.unlink()
            return p
        except (IOError, OSError):
            continue
    return Path("/tmp")


def _store_path() -> Path:
    return _store_dir() / "pr_ledger.json"


def _load() -> None:
    global _loaded, _rows, _outcomes
    if _loaded:
        return
    _loaded = True
    try:
        with open(_store_path()) as fh:
            blob = json.load(fh)
        _rows = blob.get("rows", {}) or {}
        _outcomes = blob.get("outcomes", []) or []
    except (IOError, OSError, ValueError):
        # A corrupt or absent ledger starts empty rather than raising. An
        # unreadable ledger means "we cannot attribute", which the caller already
        # handles by recording nothing -- the same degradation as a missing row.
        _rows, _outcomes = {}, []


def _persist() -> None:
    try:
        tmp = _store_path().with_suffix(".tmp")
        with open(tmp, "w") as fh:
            json.dump({"rows": _rows, "outcomes": _outcomes[-_MAX_ROWS:]}, fh)
        os.replace(tmp, _store_path())
    except (IOError, OSError):
        # Best effort. Losing a write costs one training example; raising here
        # would cost the PR that was being opened.
        pass


def record_open(pr_url: str, *, pattern_id: str, source: str, change_type: str,
                language: str, field_name: str, consumer_file: str,
                repo: str, validated, level: str) -> None:
    """Remember what produced this PR. Called when the PR is opened.

    `source` distinguishes the generator -- "pattern" (a stored FixPattern, so
    `pattern_id` is real), "template" (deterministic codemod, no pattern yet) or
    "llm". A template-generated fix has nothing to credit on merge, which is a
    fact the outcome handler needs rather than a gap it has to infer.
    """
    if not pr_url:
        return
    with _lock:
        _load()
        _rows[pr_url] = {
            "pattern_id": pattern_id or "",
            "source": source,
            "change_type": change_type,
            "language": language,
            "field_name": field_name,
            "consumer_file": consumer_file,
            "repo": repo,
            "validated": validated,
            "level": level,
            "opened_at": time.time(),
        }
        if len(_rows) > _MAX_ROWS:
            for key in sorted(_rows, key=lambda k: _rows[k].get("opened_at", 0.0)
                              )[:len(_rows) - _MAX_ROWS]:
                _rows.pop(key, None)
        _persist()


def lookup(pr_url: str) -> Optional[dict]:
    """The provenance row for a PR, or None when Ripple did not open it."""
    with _lock:
        _load()
        row = _rows.get(pr_url)
        return dict(row) if row else None


def record_outcome(pr_url: str, outcome: str, detail: dict = None) -> None:
    """Append the terminal state of a PR Ripple opened.

    Kept separate from the pattern counters on purpose: this is the audit trail of
    what the world decided, and it stays true even when the outcome is one Ripple
    must NOT learn from (a human-edited merge, a contaminated sample). The counters
    are a derived view; this is the record.
    """
    with _lock:
        _load()
        _outcomes.append({
            "pr_url": pr_url,
            "outcome": outcome,
            "at": time.time(),
            **(detail or {}),
        })
        _persist()


def all_outcomes() -> list:
    with _lock:
        _load()
        return list(_outcomes)


def stats() -> dict:
    with _lock:
        _load()
        counts: dict = {}
        for row in _outcomes:
            counts[row.get("outcome", "?")] = counts.get(row.get("outcome", "?"), 0) + 1
        return {"open_rows": len(_rows), "outcomes": len(_outcomes),
                "by_outcome": counts, "path": str(_store_path())}


def reset_for_tests() -> None:
    """Clear in-memory state. Tests only -- never called from the request path."""
    global _loaded, _rows, _outcomes
    with _lock:
        _rows, _outcomes, _loaded = {}, [], True
