#!/usr/bin/env python3
"""Stage 6 verification: prove the learning loop fires on real PR-closed payloads.

Run as TWO separate interpreters against one RIPPLE_DATA_DIR:

    phase=write   drive real payloads through the production handler
    phase=read    a FRESH process reads the stores back off disk

The two-process split is the point. importlib.reload() cannot prove
persistence -- module-level state survives inside one interpreter -- so a
separate interpreter is the only honest test that an outcome would survive a
redeploy of the container.

Every call here goes through the SAME functions the webhook calls, with the
signatures they actually have. The first draft of this file passed the wrong
keywords and died with TypeError -- the same defect class Stage 2 fixed, and
the reason the signature gate exists.

Exits non-zero on any failed assertion.
"""
from __future__ import annotations

import os
import sys

FIELD = "phoneNumberVerifyE2E"
REPO = "acme/billing-api"
CONSUMER = "packages/reporting/src/summary.ts"
APP_LOGIN = "ripple-api[bot]"

PR_CLEAN = f"https://github.com/{REPO}/pull/9001"
PR_EDITED = f"https://github.com/{REPO}/pull/9002"
PR_REJECTED = f"https://github.com/{REPO}/pull/9003"
PR_FOREIGN = f"https://github.com/{REPO}/pull/9004"


class _Change:
    """The minimum of a real BreakingChange that the provenance writer reads."""

    def __init__(self) -> None:
        self.change_type = "field_removed"
        self.field_name = FIELD
        self.field_path = FIELD
        self.description = f"{FIELD} was removed"
        self.severity = "breaking"


def _pr(url: str, merged: bool, commits: int, files: int,
        closer: str = APP_LOGIN) -> dict:
    return {
        "html_url": url,
        "url": url,
        "number": int(url.rsplit("/", 1)[1]),
        "merged": merged,
        "state": "closed",
        "title": f"fix: remove {FIELD} references",
        "body": "Generated by Ripple",
        "commits": commits,
        "changed_files": files,
        "user": {"login": APP_LOGIN},
        "merged_by": {"login": closer},
        "base": {"repo": {"full_name": REPO}},
    }


def _payload(pr: dict, commit_authors: list[str]) -> dict:
    return {
        "action": "closed",
        "pull_request": pr,
        "repository": {"full_name": REPO},
        "commits": [
            {"author": {"login": a}, "commit": {"author": {"name": a}}}
            for a in commit_authors
        ],
    }


def _find(store, *, pattern_id: str = "", field_name: str = ""):
    """`patterns` is a list, not a dict -- look a row up by identity."""
    store.load()
    for p in store.patterns:
        if pattern_id and p.pattern_id == pattern_id:
            return p
        if field_name and getattr(p, "field_name", "") == field_name:
            return p
    return None


class _Checker:
    def __init__(self) -> None:
        self.failures: list[str] = []

    def __call__(self, label: str, got, want) -> None:
        ok = got == want
        print(f"  {'ok  ' if ok else 'FAIL'}  {label}: got={got!r} want={want!r}")
        if not ok:
            self.failures.append(label)

    def verdict(self, phase: str) -> int:
        if self.failures:
            print(f"\n  phase={phase}  FAIL: {', '.join(self.failures)}")
            return 1
        print(f"\n  phase={phase}  PASS")
        return 0


def _open_pr(webhook, url: str, explanation: str) -> None:
    """Exactly what the three platform loops do when a PR opens."""
    webhook._record_pr_provenance(
        url,
        platform="github",
        repo=REPO,
        change=_Change(),
        consumer_file=CONSUMER,
        language="typescript",
        explanation=explanation,
        validated=True,
        level="AUTO",
    )


def phase_write() -> int:
    from app import pr_ledger, webhook
    from app.rag_store import rag_store

    check = _Checker()

    # --- 1. PR creation writes an attributable provenance row ------------
    _open_pr(webhook, PR_CLEAN, "[template] removed the field reference")
    check("clean PR is attributable", pr_ledger.lookup(PR_CLEAN) is not None, True)
    check("a PR we never opened is NOT ours", pr_ledger.lookup(PR_FOREIGN), None)

    row = pr_ledger.lookup(PR_CLEAN) or {}
    check("template fix credits no pattern", row.get("pattern_id"), "")
    check("source derived from the explanation prefix", row.get("source"), "template")

    pid = rag_store.make_pattern_id(
        row.get("change_type", ""), "typescript", FIELD)
    check("store holds no pattern before any merge",
          _find(rag_store, pattern_id=pid), None)

    # --- 2. clean merge DERIVES the pattern ------------------------------
    pr = _pr(PR_CLEAN, merged=True, commits=1, files=1)
    r1 = webhook._record_pr_terminal(pr, _payload(pr, [APP_LOGIN]), merged=True)
    print(f"     clean merge      -> {r1}")
    check("clean merge classified", r1.get("outcome"), "merged_clean")

    p = _find(rag_store, field_name=FIELD)
    check("clean merge DERIVED a pattern", p is not None, True)
    if p:
        check("derived provenance", p.provenance, "merged_clean")
        check("merge_count credited", p.merge_count, 1)

    # --- 3. human-edited merge: no credit, but it OWNS the strategy ------
    _open_pr(webhook, PR_EDITED, f"[RAG/{pid}] applied a learned pattern")
    pr = _pr(PR_EDITED, merged=True, commits=2, files=1, closer="a-human")
    r2 = webhook._record_pr_terminal(
        pr, _payload(pr, [APP_LOGIN, "a-human"]), merged=True)
    print(f"     human-edited     -> {r2}")
    check("human edit classified", r2.get("outcome"), "merged_with_edits")
    check("one follow-up commit on one file IS attributable",
          r2.get("contaminated"), False)

    p = _find(rag_store, field_name=FIELD)
    if p:
        check("merge_count NOT raised by a rescued merge", p.merge_count, 1)
        check("provenance raised to human_edit", p.provenance, "human_edit")

    # --- 4. rejection: evidence accumulates from any source --------------
    _open_pr(webhook, PR_REJECTED, f"[RAG/{pid}] applied a learned pattern")
    pr = _pr(PR_REJECTED, merged=False, commits=1, files=1)
    r3 = webhook._record_pr_terminal(pr, _payload(pr, [APP_LOGIN]), merged=False)
    print(f"     rejected         -> {r3}")
    check("rejection classified", r3.get("outcome"), "rejected")

    p = _find(rag_store, field_name=FIELD)
    if p:
        check("reject_count rose", p.reject_count, 1)
        check("strategy still owned by human_edit", p.provenance, "human_edit")

    # --- 5. a PR we never opened teaches nothing -------------------------
    before = len(rag_store.patterns)
    pr = _pr(PR_FOREIGN, merged=True, commits=1, files=1, closer="someone-else")
    r4 = webhook._record_pr_terminal(
        pr, _payload(pr, ["someone-else"]), merged=True)
    print(f"     foreign PR       -> {r4}")
    check("foreign PR unattributed", r4.get("status"), "unattributed")
    check("foreign PR has no outcome at all", r4.get("outcome"), None)
    check("foreign PR added no pattern", len(rag_store.patterns), before)

    # --- 6a. a MANY-commit edit is contaminated: no provenance raise ------
    url6a = f"https://github.com/{REPO}/pull/9006"
    _open_pr(webhook, url6a, f"[RAG/{pid}] applied a learned pattern")
    pr = _pr(url6a, merged=True, commits=4, files=1, closer="a-human")
    r6a = webhook._record_pr_terminal(
        pr, _payload(pr, [APP_LOGIN, "a-human", "a-human", "a-human"]), merged=True)
    print(f"     4-commit edit    -> {r6a}")
    check("a 4-commit edit is contaminated", r6a.get("contaminated"), True)
    check("contaminated edit credits no counters",
          r6a.get("counters_updated"), False)

    # --- 6b. a contaminated merge is recorded but teaches nothing ---------
    url = f"https://github.com/{REPO}/pull/9005"
    _open_pr(webhook, url, f"[RAG/{pid}] applied a learned pattern")
    pr = _pr(url, merged=True, commits=1, files=7)
    r5 = webhook._record_pr_terminal(pr, _payload(pr, [APP_LOGIN]), merged=True)
    print(f"     contaminated     -> {r5}")
    p = _find(rag_store, field_name=FIELD)
    if p:
        check("contaminated merge did NOT credit merge_count", p.merge_count, 1)

    # --- 7. THE ladder property: an inferred guess may not overwrite a human --
    #
    # Without this step the gate claimed "ladder held" while never attempting the
    # write the ladder exists to block -- and a mutation that made
    # _may_replace_strategy() return True unconditionally passed it. The
    # regression suite caught that mutation, but a gate whose PASS message
    # asserts a property it does not exercise is exactly the fail-silent shape
    # this repo gates against.
    from app.rag_store import FixPattern

    human_strategy = (p.strategy if p else "")
    rag_store.add_pattern(FixPattern(
        pattern_id=pid,
        change_type=row.get("change_type", ""),
        language="typescript",
        field_name=FIELD,
        strategy="A CORPUS GUESS TRYING TO OVERWRITE A HUMAN CORRECTION",
        provenance="inferred",
        reject_count=1,
        last_used=__import__("time").time(),
    ))
    # add_pattern() mutates in memory and does NOT persist -- persistence is the
    # caller's job, which every production call site does and which THIS caller
    # forgot on its first draft. The in-memory count read 2 while the volume held
    # 1, so phase=read passed against a stale row. Pinned by
    # test_every_add_pattern_caller_persists.
    rag_store.save()
    p = _find(rag_store, field_name=FIELD)
    if p:
        check("inferred write did NOT take the strategy", p.strategy, human_strategy)
        check("inferred write did NOT take provenance", p.provenance, "human_edit")
        check("but its EVIDENCE still accumulated", p.reject_count, 2)

    print(f"\n  pattern_id {pid}")
    return check.verdict("write")


def phase_read() -> int:
    """A FRESH interpreter. Nothing is in memory; it all comes off disk."""
    from app import pr_ledger
    from app.rag_store import rag_store

    check = _Checker()

    p = _find(rag_store, field_name=FIELD)
    pid = p.pattern_id if p else "<absent>"

    check("pattern survived process death", p is not None, True)
    if p:
        check("provenance survived", p.provenance, "human_edit")
        check("merge_count survived", p.merge_count, 1)
        # 2, not 1: one rejected PR plus the inferred write's evidence. This
        # asserted 1 and PASSED against a row the write phase had left stale on
        # disk -- the in-memory store read 2 while the volume held 1. A read-back
        # assertion that agrees with a stale row proves nothing.
        check("reject_count survived (evidence from BOTH sources)",
              p.reject_count, 2)

    outcomes = {o.get("pr_url"): o.get("outcome") for o in pr_ledger.all_outcomes()}
    check("clean outcome persisted", outcomes.get(PR_CLEAN), "merged_clean")
    check("edited outcome persisted", outcomes.get(PR_EDITED), "merged_with_edits")
    check("rejected outcome persisted", outcomes.get(PR_REJECTED), "rejected")
    check("foreign PR left NO ledger outcome", PR_FOREIGN in outcomes, False)

    print(f"\n  pattern_id {pid}")
    return check.verdict("read")


def phase_both() -> int:
    """Run write then read as TWO real subprocesses in a scratch dir.

    Exists so this file is a single gate entry. It creates and removes its own
    RIPPLE_DATA_DIR -- a verifier that writes rows into the mounted volume every
    time the suite runs is a slow leak, which is the trap the Stage 3 test fell
    into by growing a persisted file by one row per run.
    """
    import shutil
    import subprocess
    import tempfile

    here = os.path.abspath(__file__)
    scratch = tempfile.mkdtemp(prefix="ripple_learning_verify_")
    env = dict(os.environ, RIPPLE_DATA_DIR=scratch)
    try:
        for phase in ("write", "read"):
            proc = subprocess.run([sys.executable, here, phase], env=env,
                                  capture_output=True, text=True, timeout=300)
            sys.stdout.write(proc.stdout)
            if proc.returncode != 0:
                sys.stdout.write(proc.stderr)
                print(f"\n  learning loop: FAIL in phase={phase}")
                return 1
        print("  learning loop: PASS -- outcomes attributed, ladder held, "
              "state survived a separate interpreter")
        return 0
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    phase = sys.argv[1] if len(sys.argv) > 1 else "both"
    if phase == "both":
        sys.exit(phase_both())
    if not os.environ.get("RIPPLE_DATA_DIR"):
        print("refusing to run without RIPPLE_DATA_DIR -- this writes real rows")
        sys.exit(2)
    print(f"\n=== verify_learning_loop  phase={phase}  "
          f"data={os.environ['RIPPLE_DATA_DIR']}")
    sys.exit(phase_write() if phase == "write" else phase_read())
